//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ARModel", "FK_Sales_CustomerId", "CREDITOR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(athena.AR.Data.CREDITOR), "SALE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.SALE), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FOREIGN", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "CREDITOR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.CREDITOR), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_PayMent_ARId", "RECEIVABLE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(athena.AR.Data.RECEIVABLE), "PAYMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.PAYMENT), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_PayMent_LastModifiedBy_UserId", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "PAYMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.PAYMENT), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_AR_LastModifiedBy_UserId", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "RECEIVABLE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.RECEIVABLE), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_AR_SalesId", "SALE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.SALE), "RECEIVABLE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.RECEIVABLE), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_Sales_LastModifiedBy_UserId", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "SALE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.SALE), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_ReceivableInterest_Id", "SALE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(athena.AR.Data.SALE), "RECEIVABLEINTEREST", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.RECEIVABLEINTEREST), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_ReceivableInterest_UserId", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "RECEIVABLEINTEREST", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.RECEIVABLEINTEREST), true)]
[assembly: EdmRelationshipAttribute("ARModel", "FK_UserLog_UserId", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(athena.AR.Data.USER), "USERLOG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(athena.AR.Data.USERLOG), true)]

#endregion

namespace athena.AR.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AREntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AREntities object using the connection string found in the 'AREntities' section of the application configuration file.
        /// </summary>
        public AREntities() : base("name=AREntities", "AREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AREntities object.
        /// </summary>
        public AREntities(string connectionString) : base(connectionString, "AREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AREntities object.
        /// </summary>
        public AREntities(EntityConnection connection) : base(connection, "AREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USER> USERs
        {
            get
            {
                if ((_USERs == null))
                {
                    _USERs = base.CreateObjectSet<USER>("USERs");
                }
                return _USERs;
            }
        }
        private ObjectSet<USER> _USERs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CREDITOR> CREDITORs
        {
            get
            {
                if ((_CREDITORs == null))
                {
                    _CREDITORs = base.CreateObjectSet<CREDITOR>("CREDITORs");
                }
                return _CREDITORs;
            }
        }
        private ObjectSet<CREDITOR> _CREDITORs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PAYMENT> PAYMENTs
        {
            get
            {
                if ((_PAYMENTs == null))
                {
                    _PAYMENTs = base.CreateObjectSet<PAYMENT>("PAYMENTs");
                }
                return _PAYMENTs;
            }
        }
        private ObjectSet<PAYMENT> _PAYMENTs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RECEIVABLE> RECEIVABLEs
        {
            get
            {
                if ((_RECEIVABLEs == null))
                {
                    _RECEIVABLEs = base.CreateObjectSet<RECEIVABLE>("RECEIVABLEs");
                }
                return _RECEIVABLEs;
            }
        }
        private ObjectSet<RECEIVABLE> _RECEIVABLEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SALE> SALES
        {
            get
            {
                if ((_SALES == null))
                {
                    _SALES = base.CreateObjectSet<SALE>("SALES");
                }
                return _SALES;
            }
        }
        private ObjectSet<SALE> _SALES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RECEIVABLEINTEREST> RECEIVABLEINTERESTs
        {
            get
            {
                if ((_RECEIVABLEINTERESTs == null))
                {
                    _RECEIVABLEINTERESTs = base.CreateObjectSet<RECEIVABLEINTEREST>("RECEIVABLEINTERESTs");
                }
                return _RECEIVABLEINTERESTs;
            }
        }
        private ObjectSet<RECEIVABLEINTEREST> _RECEIVABLEINTERESTs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USERLOG> USERLOGs
        {
            get
            {
                if ((_USERLOGs == null))
                {
                    _USERLOGs = base.CreateObjectSet<USERLOG>("USERLOGs");
                }
                return _USERLOGs;
            }
        }
        private ObjectSet<USERLOG> _USERLOGs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSERs(USER uSER)
        {
            base.AddObject("USERs", uSER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CREDITORs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCREDITORs(CREDITOR cREDITOR)
        {
            base.AddObject("CREDITORs", cREDITOR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PAYMENTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPAYMENTs(PAYMENT pAYMENT)
        {
            base.AddObject("PAYMENTs", pAYMENT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RECEIVABLEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRECEIVABLEs(RECEIVABLE rECEIVABLE)
        {
            base.AddObject("RECEIVABLEs", rECEIVABLE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SALES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSALES(SALE sALE)
        {
            base.AddObject("SALES", sALE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RECEIVABLEINTERESTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRECEIVABLEINTERESTs(RECEIVABLEINTEREST rECEIVABLEINTEREST)
        {
            base.AddObject("RECEIVABLEINTERESTs", rECEIVABLEINTEREST);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USERLOGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSERLOGs(USERLOG uSERLOG)
        {
            base.AddObject("USERLOGs", uSERLOG);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="CREDITOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CREDITOR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CREDITOR object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        /// <param name="aCTIVE">Initial value of the ACTIVE property.</param>
        /// <param name="lASTDATEMODIFIED">Initial value of the LASTDATEMODIFIED property.</param>
        public static CREDITOR CreateCREDITOR(global::System.Int32 id, global::System.String nAME, global::System.Int32 aCTIVE, global::System.DateTime lASTDATEMODIFIED)
        {
            CREDITOR cREDITOR = new CREDITOR();
            cREDITOR.ID = id;
            cREDITOR.NAME = nAME;
            cREDITOR.ACTIVE = aCTIVE;
            cREDITOR.LASTDATEMODIFIED = lASTDATEMODIFIED;
            return cREDITOR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ACTIVE
        {
            get
            {
                return _ACTIVE;
            }
            set
            {
                OnACTIVEChanging(value);
                ReportPropertyChanging("ACTIVE");
                _ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTIVE");
                OnACTIVEChanged();
            }
        }
        private global::System.Int32 _ACTIVE;
        partial void OnACTIVEChanging(global::System.Int32 value);
        partial void OnACTIVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LASTMODIFIEDBY
        {
            get
            {
                return _LASTMODIFIEDBY;
            }
            set
            {
                OnLASTMODIFIEDBYChanging(value);
                ReportPropertyChanging("LASTMODIFIEDBY");
                _LASTMODIFIEDBY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDBY");
                OnLASTMODIFIEDBYChanged();
            }
        }
        private Nullable<global::System.Int32> _LASTMODIFIEDBY;
        partial void OnLASTMODIFIEDBYChanging(Nullable<global::System.Int32> value);
        partial void OnLASTMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTDATEMODIFIED
        {
            get
            {
                return _LASTDATEMODIFIED;
            }
            set
            {
                OnLASTDATEMODIFIEDChanging(value);
                ReportPropertyChanging("LASTDATEMODIFIED");
                _LASTDATEMODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTDATEMODIFIED");
                OnLASTDATEMODIFIEDChanged();
            }
        }
        private global::System.DateTime _LASTDATEMODIFIED;
        partial void OnLASTDATEMODIFIEDChanging(global::System.DateTime value);
        partial void OnLASTDATEMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATECREATED
        {
            get
            {
                return _DATECREATED;
            }
            set
            {
                OnDATECREATEDChanging(value);
                ReportPropertyChanging("DATECREATED");
                _DATECREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATECREATED");
                OnDATECREATEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATECREATED;
        partial void OnDATECREATEDChanging(Nullable<global::System.DateTime> value);
        partial void OnDATECREATEDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_Sales_CustomerId", "SALE")]
        public EntityCollection<SALE> SALES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SALE>("ARModel.FK_Sales_CustomerId", "SALE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SALE>("ARModel.FK_Sales_CustomerId", "SALE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FOREIGN", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FOREIGN", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FOREIGN", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FOREIGN", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FOREIGN", "USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="PAYMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PAYMENT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PAYMENT object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="rECEIVABLEID">Initial value of the RECEIVABLEID property.</param>
        /// <param name="aMOUNT">Initial value of the AMOUNT property.</param>
        /// <param name="lASTMODIFIEDDATE">Initial value of the LASTMODIFIEDDATE property.</param>
        /// <param name="pAYMENTDATE">Initial value of the PAYMENTDATE property.</param>
        public static PAYMENT CreatePAYMENT(global::System.Int32 id, global::System.Int32 rECEIVABLEID, global::System.Decimal aMOUNT, global::System.DateTime lASTMODIFIEDDATE, global::System.DateTime pAYMENTDATE)
        {
            PAYMENT pAYMENT = new PAYMENT();
            pAYMENT.ID = id;
            pAYMENT.RECEIVABLEID = rECEIVABLEID;
            pAYMENT.AMOUNT = aMOUNT;
            pAYMENT.LASTMODIFIEDDATE = lASTMODIFIEDDATE;
            pAYMENT.PAYMENTDATE = pAYMENTDATE;
            return pAYMENT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RECEIVABLEID
        {
            get
            {
                return _RECEIVABLEID;
            }
            set
            {
                OnRECEIVABLEIDChanging(value);
                ReportPropertyChanging("RECEIVABLEID");
                _RECEIVABLEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RECEIVABLEID");
                OnRECEIVABLEIDChanged();
            }
        }
        private global::System.Int32 _RECEIVABLEID;
        partial void OnRECEIVABLEIDChanging(global::System.Int32 value);
        partial void OnRECEIVABLEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AMOUNT
        {
            get
            {
                return _AMOUNT;
            }
            set
            {
                OnAMOUNTChanging(value);
                ReportPropertyChanging("AMOUNT");
                _AMOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNT");
                OnAMOUNTChanged();
            }
        }
        private global::System.Decimal _AMOUNT;
        partial void OnAMOUNTChanging(global::System.Decimal value);
        partial void OnAMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LASTMODIFIEDBY
        {
            get
            {
                return _LASTMODIFIEDBY;
            }
            set
            {
                OnLASTMODIFIEDBYChanging(value);
                ReportPropertyChanging("LASTMODIFIEDBY");
                _LASTMODIFIEDBY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDBY");
                OnLASTMODIFIEDBYChanged();
            }
        }
        private Nullable<global::System.Int32> _LASTMODIFIEDBY;
        partial void OnLASTMODIFIEDBYChanging(Nullable<global::System.Int32> value);
        partial void OnLASTMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIEDDATE
        {
            get
            {
                return _LASTMODIFIEDDATE;
            }
            set
            {
                OnLASTMODIFIEDDATEChanging(value);
                ReportPropertyChanging("LASTMODIFIEDDATE");
                _LASTMODIFIEDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDDATE");
                OnLASTMODIFIEDDATEChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIEDDATE;
        partial void OnLASTMODIFIEDDATEChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PAYMENTDATE
        {
            get
            {
                return _PAYMENTDATE;
            }
            set
            {
                OnPAYMENTDATEChanging(value);
                ReportPropertyChanging("PAYMENTDATE");
                _PAYMENTDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAYMENTDATE");
                OnPAYMENTDATEChanged();
            }
        }
        private global::System.DateTime _PAYMENTDATE;
        partial void OnPAYMENTDATEChanging(global::System.DateTime value);
        partial void OnPAYMENTDATEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_PayMent_ARId", "RECEIVABLE")]
        public RECEIVABLE RECEIVABLE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RECEIVABLE>("ARModel.FK_PayMent_ARId", "RECEIVABLE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RECEIVABLE>("ARModel.FK_PayMent_ARId", "RECEIVABLE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RECEIVABLE> RECEIVABLEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RECEIVABLE>("ARModel.FK_PayMent_ARId", "RECEIVABLE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RECEIVABLE>("ARModel.FK_PayMent_ARId", "RECEIVABLE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_PayMent_LastModifiedBy_UserId", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_PayMent_LastModifiedBy_UserId", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_PayMent_LastModifiedBy_UserId", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_PayMent_LastModifiedBy_UserId", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FK_PayMent_LastModifiedBy_UserId", "USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="RECEIVABLE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RECEIVABLE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RECEIVABLE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="aMOUNTDUE">Initial value of the AMOUNTDUE property.</param>
        /// <param name="dUEDATE">Initial value of the DUEDATE property.</param>
        /// <param name="iSPAID">Initial value of the ISPAID property.</param>
        /// <param name="lASTMODIFIEDDATE">Initial value of the LASTMODIFIEDDATE property.</param>
        public static RECEIVABLE CreateRECEIVABLE(global::System.Int32 id, global::System.Decimal aMOUNTDUE, global::System.DateTime dUEDATE, global::System.Int32 iSPAID, global::System.DateTime lASTMODIFIEDDATE)
        {
            RECEIVABLE rECEIVABLE = new RECEIVABLE();
            rECEIVABLE.ID = id;
            rECEIVABLE.AMOUNTDUE = aMOUNTDUE;
            rECEIVABLE.DUEDATE = dUEDATE;
            rECEIVABLE.ISPAID = iSPAID;
            rECEIVABLE.LASTMODIFIEDDATE = lASTMODIFIEDDATE;
            return rECEIVABLE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SALESID
        {
            get
            {
                return _SALESID;
            }
            set
            {
                OnSALESIDChanging(value);
                ReportPropertyChanging("SALESID");
                _SALESID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SALESID");
                OnSALESIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SALESID;
        partial void OnSALESIDChanging(Nullable<global::System.Int32> value);
        partial void OnSALESIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AMOUNTDUE
        {
            get
            {
                return _AMOUNTDUE;
            }
            set
            {
                OnAMOUNTDUEChanging(value);
                ReportPropertyChanging("AMOUNTDUE");
                _AMOUNTDUE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNTDUE");
                OnAMOUNTDUEChanged();
            }
        }
        private global::System.Decimal _AMOUNTDUE;
        partial void OnAMOUNTDUEChanging(global::System.Decimal value);
        partial void OnAMOUNTDUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DUEDATE
        {
            get
            {
                return _DUEDATE;
            }
            set
            {
                OnDUEDATEChanging(value);
                ReportPropertyChanging("DUEDATE");
                _DUEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DUEDATE");
                OnDUEDATEChanged();
            }
        }
        private global::System.DateTime _DUEDATE;
        partial void OnDUEDATEChanging(global::System.DateTime value);
        partial void OnDUEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BALANCE
        {
            get
            {
                return _BALANCE;
            }
            set
            {
                OnBALANCEChanging(value);
                ReportPropertyChanging("BALANCE");
                _BALANCE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BALANCE");
                OnBALANCEChanged();
            }
        }
        private Nullable<global::System.Decimal> _BALANCE;
        partial void OnBALANCEChanging(Nullable<global::System.Decimal> value);
        partial void OnBALANCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ISPAID
        {
            get
            {
                return _ISPAID;
            }
            set
            {
                OnISPAIDChanging(value);
                ReportPropertyChanging("ISPAID");
                _ISPAID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISPAID");
                OnISPAIDChanged();
            }
        }
        private global::System.Int32 _ISPAID;
        partial void OnISPAIDChanging(global::System.Int32 value);
        partial void OnISPAIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LASTMODIFIEDBYID
        {
            get
            {
                return _LASTMODIFIEDBYID;
            }
            set
            {
                OnLASTMODIFIEDBYIDChanging(value);
                ReportPropertyChanging("LASTMODIFIEDBYID");
                _LASTMODIFIEDBYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDBYID");
                OnLASTMODIFIEDBYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LASTMODIFIEDBYID;
        partial void OnLASTMODIFIEDBYIDChanging(Nullable<global::System.Int32> value);
        partial void OnLASTMODIFIEDBYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIEDDATE
        {
            get
            {
                return _LASTMODIFIEDDATE;
            }
            set
            {
                OnLASTMODIFIEDDATEChanging(value);
                ReportPropertyChanging("LASTMODIFIEDDATE");
                _LASTMODIFIEDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDDATE");
                OnLASTMODIFIEDDATEChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIEDDATE;
        partial void OnLASTMODIFIEDDATEChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATECREATED
        {
            get
            {
                return _DATECREATED;
            }
            set
            {
                OnDATECREATEDChanging(value);
                ReportPropertyChanging("DATECREATED");
                _DATECREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATECREATED");
                OnDATECREATEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATECREATED;
        partial void OnDATECREATEDChanging(Nullable<global::System.DateTime> value);
        partial void OnDATECREATEDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_PayMent_ARId", "PAYMENT")]
        public EntityCollection<PAYMENT> PAYMENTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PAYMENT>("ARModel.FK_PayMent_ARId", "PAYMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PAYMENT>("ARModel.FK_PayMent_ARId", "PAYMENT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_AR_LastModifiedBy_UserId", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_AR_LastModifiedBy_UserId", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_AR_LastModifiedBy_UserId", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_AR_LastModifiedBy_UserId", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FK_AR_LastModifiedBy_UserId", "USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_AR_SalesId", "SALE")]
        public SALE SALE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_AR_SalesId", "SALE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_AR_SalesId", "SALE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SALE> SALEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_AR_SalesId", "SALE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SALE>("ARModel.FK_AR_SalesId", "SALE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="RECEIVABLEINTEREST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RECEIVABLEINTEREST : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RECEIVABLEINTEREST object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sALESID">Initial value of the SALESID property.</param>
        /// <param name="mONTHSTOPAY">Initial value of the MONTHSTOPAY property.</param>
        /// <param name="mONTHLYINTEREST">Initial value of the MONTHLYINTEREST property.</param>
        /// <param name="lASTMODIFIEDDATE">Initial value of the LASTMODIFIEDDATE property.</param>
        public static RECEIVABLEINTEREST CreateRECEIVABLEINTEREST(global::System.Int32 id, global::System.Int32 sALESID, global::System.Int32 mONTHSTOPAY, global::System.Decimal mONTHLYINTEREST, global::System.DateTime lASTMODIFIEDDATE)
        {
            RECEIVABLEINTEREST rECEIVABLEINTEREST = new RECEIVABLEINTEREST();
            rECEIVABLEINTEREST.ID = id;
            rECEIVABLEINTEREST.SALESID = sALESID;
            rECEIVABLEINTEREST.MONTHSTOPAY = mONTHSTOPAY;
            rECEIVABLEINTEREST.MONTHLYINTEREST = mONTHLYINTEREST;
            rECEIVABLEINTEREST.LASTMODIFIEDDATE = lASTMODIFIEDDATE;
            return rECEIVABLEINTEREST;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SALESID
        {
            get
            {
                return _SALESID;
            }
            set
            {
                OnSALESIDChanging(value);
                ReportPropertyChanging("SALESID");
                _SALESID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SALESID");
                OnSALESIDChanged();
            }
        }
        private global::System.Int32 _SALESID;
        partial void OnSALESIDChanging(global::System.Int32 value);
        partial void OnSALESIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MONTHSTOPAY
        {
            get
            {
                return _MONTHSTOPAY;
            }
            set
            {
                OnMONTHSTOPAYChanging(value);
                ReportPropertyChanging("MONTHSTOPAY");
                _MONTHSTOPAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTHSTOPAY");
                OnMONTHSTOPAYChanged();
            }
        }
        private global::System.Int32 _MONTHSTOPAY;
        partial void OnMONTHSTOPAYChanging(global::System.Int32 value);
        partial void OnMONTHSTOPAYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MONTHLYINTEREST
        {
            get
            {
                return _MONTHLYINTEREST;
            }
            set
            {
                OnMONTHLYINTERESTChanging(value);
                ReportPropertyChanging("MONTHLYINTEREST");
                _MONTHLYINTEREST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTHLYINTEREST");
                OnMONTHLYINTERESTChanged();
            }
        }
        private global::System.Decimal _MONTHLYINTEREST;
        partial void OnMONTHLYINTERESTChanging(global::System.Decimal value);
        partial void OnMONTHLYINTERESTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LASTMODIFIEDBY
        {
            get
            {
                return _LASTMODIFIEDBY;
            }
            set
            {
                OnLASTMODIFIEDBYChanging(value);
                ReportPropertyChanging("LASTMODIFIEDBY");
                _LASTMODIFIEDBY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDBY");
                OnLASTMODIFIEDBYChanged();
            }
        }
        private Nullable<global::System.Int32> _LASTMODIFIEDBY;
        partial void OnLASTMODIFIEDBYChanging(Nullable<global::System.Int32> value);
        partial void OnLASTMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIEDDATE
        {
            get
            {
                return _LASTMODIFIEDDATE;
            }
            set
            {
                OnLASTMODIFIEDDATEChanging(value);
                ReportPropertyChanging("LASTMODIFIEDDATE");
                _LASTMODIFIEDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDDATE");
                OnLASTMODIFIEDDATEChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIEDDATE;
        partial void OnLASTMODIFIEDDATEChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDDATEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_ReceivableInterest_Id", "SALE")]
        public SALE SALE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_ReceivableInterest_Id", "SALE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_ReceivableInterest_Id", "SALE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SALE> SALEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALE>("ARModel.FK_ReceivableInterest_Id", "SALE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SALE>("ARModel.FK_ReceivableInterest_Id", "SALE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_ReceivableInterest_UserId", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_ReceivableInterest_UserId", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_ReceivableInterest_UserId", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_ReceivableInterest_UserId", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FK_ReceivableInterest_UserId", "USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="SALE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SALE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SALE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cUSTOMERID">Initial value of the CUSTOMERID property.</param>
        /// <param name="iTEM">Initial value of the ITEM property.</param>
        /// <param name="qTY">Initial value of the QTY property.</param>
        /// <param name="uNITPRICE">Initial value of the UNITPRICE property.</param>
        /// <param name="tOTALPRICE">Initial value of the TOTALPRICE property.</param>
        /// <param name="sALESDATE">Initial value of the SALESDATE property.</param>
        /// <param name="lASTMODIFIEDDATE">Initial value of the LASTMODIFIEDDATE property.</param>
        public static SALE CreateSALE(global::System.Int32 id, global::System.Int32 cUSTOMERID, global::System.String iTEM, global::System.Int32 qTY, global::System.Decimal uNITPRICE, global::System.Decimal tOTALPRICE, global::System.DateTime sALESDATE, global::System.DateTime lASTMODIFIEDDATE)
        {
            SALE sALE = new SALE();
            sALE.ID = id;
            sALE.CUSTOMERID = cUSTOMERID;
            sALE.ITEM = iTEM;
            sALE.QTY = qTY;
            sALE.UNITPRICE = uNITPRICE;
            sALE.TOTALPRICE = tOTALPRICE;
            sALE.SALESDATE = sALESDATE;
            sALE.LASTMODIFIEDDATE = lASTMODIFIEDDATE;
            return sALE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CUSTOMERID
        {
            get
            {
                return _CUSTOMERID;
            }
            set
            {
                OnCUSTOMERIDChanging(value);
                ReportPropertyChanging("CUSTOMERID");
                _CUSTOMERID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUSTOMERID");
                OnCUSTOMERIDChanged();
            }
        }
        private global::System.Int32 _CUSTOMERID;
        partial void OnCUSTOMERIDChanging(global::System.Int32 value);
        partial void OnCUSTOMERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ITEM
        {
            get
            {
                return _ITEM;
            }
            set
            {
                OnITEMChanging(value);
                ReportPropertyChanging("ITEM");
                _ITEM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ITEM");
                OnITEMChanged();
            }
        }
        private global::System.String _ITEM;
        partial void OnITEMChanging(global::System.String value);
        partial void OnITEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QTY
        {
            get
            {
                return _QTY;
            }
            set
            {
                OnQTYChanging(value);
                ReportPropertyChanging("QTY");
                _QTY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QTY");
                OnQTYChanged();
            }
        }
        private global::System.Int32 _QTY;
        partial void OnQTYChanging(global::System.Int32 value);
        partial void OnQTYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal UNITPRICE
        {
            get
            {
                return _UNITPRICE;
            }
            set
            {
                OnUNITPRICEChanging(value);
                ReportPropertyChanging("UNITPRICE");
                _UNITPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UNITPRICE");
                OnUNITPRICEChanged();
            }
        }
        private global::System.Decimal _UNITPRICE;
        partial void OnUNITPRICEChanging(global::System.Decimal value);
        partial void OnUNITPRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TOTALPRICE
        {
            get
            {
                return _TOTALPRICE;
            }
            set
            {
                OnTOTALPRICEChanging(value);
                ReportPropertyChanging("TOTALPRICE");
                _TOTALPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TOTALPRICE");
                OnTOTALPRICEChanged();
            }
        }
        private global::System.Decimal _TOTALPRICE;
        partial void OnTOTALPRICEChanging(global::System.Decimal value);
        partial void OnTOTALPRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SALESDATE
        {
            get
            {
                return _SALESDATE;
            }
            set
            {
                OnSALESDATEChanging(value);
                ReportPropertyChanging("SALESDATE");
                _SALESDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SALESDATE");
                OnSALESDATEChanged();
            }
        }
        private global::System.DateTime _SALESDATE;
        partial void OnSALESDATEChanging(global::System.DateTime value);
        partial void OnSALESDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LASTMODIFIEDBY
        {
            get
            {
                return _LASTMODIFIEDBY;
            }
            set
            {
                OnLASTMODIFIEDBYChanging(value);
                ReportPropertyChanging("LASTMODIFIEDBY");
                _LASTMODIFIEDBY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDBY");
                OnLASTMODIFIEDBYChanged();
            }
        }
        private Nullable<global::System.Int32> _LASTMODIFIEDBY;
        partial void OnLASTMODIFIEDBYChanging(Nullable<global::System.Int32> value);
        partial void OnLASTMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIEDDATE
        {
            get
            {
                return _LASTMODIFIEDDATE;
            }
            set
            {
                OnLASTMODIFIEDDATEChanging(value);
                ReportPropertyChanging("LASTMODIFIEDDATE");
                _LASTMODIFIEDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIEDDATE");
                OnLASTMODIFIEDDATEChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIEDDATE;
        partial void OnLASTMODIFIEDDATEChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDDATEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_Sales_CustomerId", "CREDITOR")]
        public CREDITOR CREDITOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CREDITOR>("ARModel.FK_Sales_CustomerId", "CREDITOR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CREDITOR>("ARModel.FK_Sales_CustomerId", "CREDITOR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CREDITOR> CREDITORReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CREDITOR>("ARModel.FK_Sales_CustomerId", "CREDITOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CREDITOR>("ARModel.FK_Sales_CustomerId", "CREDITOR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_AR_SalesId", "RECEIVABLE")]
        public EntityCollection<RECEIVABLE> RECEIVABLEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RECEIVABLE>("ARModel.FK_AR_SalesId", "RECEIVABLE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RECEIVABLE>("ARModel.FK_AR_SalesId", "RECEIVABLE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_Sales_LastModifiedBy_UserId", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_Sales_LastModifiedBy_UserId", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_Sales_LastModifiedBy_UserId", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_Sales_LastModifiedBy_UserId", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FK_Sales_LastModifiedBy_UserId", "USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_ReceivableInterest_Id", "RECEIVABLEINTEREST")]
        public EntityCollection<RECEIVABLEINTEREST> RECEIVABLEINTERESTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RECEIVABLEINTEREST>("ARModel.FK_ReceivableInterest_Id", "RECEIVABLEINTEREST");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RECEIVABLEINTEREST>("ARModel.FK_ReceivableInterest_Id", "RECEIVABLEINTEREST", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USER object.
        /// </summary>
        /// <param name="uSERID">Initial value of the USERID property.</param>
        /// <param name="uSERNAME">Initial value of the USERNAME property.</param>
        /// <param name="pASSWORD">Initial value of the PASSWORD property.</param>
        /// <param name="aCTIVE">Initial value of the ACTIVE property.</param>
        /// <param name="lOGGED">Initial value of the LOGGED property.</param>
        public static USER CreateUSER(global::System.Int32 uSERID, global::System.String uSERNAME, global::System.String pASSWORD, global::System.Int16 aCTIVE, global::System.Int16 lOGGED)
        {
            USER uSER = new USER();
            uSER.USERID = uSERID;
            uSER.USERNAME = uSERNAME;
            uSER.PASSWORD = pASSWORD;
            uSER.ACTIVE = aCTIVE;
            uSER.LOGGED = lOGGED;
            return uSER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                if (_USERID != value)
                {
                    OnUSERIDChanging(value);
                    ReportPropertyChanging("USERID");
                    _USERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USERID");
                    OnUSERIDChanged();
                }
            }
        }
        private global::System.Int32 _USERID;
        partial void OnUSERIDChanging(global::System.Int32 value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                OnUSERNAMEChanging(value);
                ReportPropertyChanging("USERNAME");
                _USERNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USERNAME");
                OnUSERNAMEChanged();
            }
        }
        private global::System.String _USERNAME;
        partial void OnUSERNAMEChanging(global::System.String value);
        partial void OnUSERNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATEDDATE
        {
            get
            {
                return _CREATEDDATE;
            }
            set
            {
                OnCREATEDDATEChanging(value);
                ReportPropertyChanging("CREATEDDATE");
                _CREATEDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATEDDATE");
                OnCREATEDDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATEDDATE;
        partial void OnCREATEDDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATEDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ACTIVE
        {
            get
            {
                return _ACTIVE;
            }
            set
            {
                OnACTIVEChanging(value);
                ReportPropertyChanging("ACTIVE");
                _ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTIVE");
                OnACTIVEChanged();
            }
        }
        private global::System.Int16 _ACTIVE;
        partial void OnACTIVEChanging(global::System.Int16 value);
        partial void OnACTIVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LOGGED
        {
            get
            {
                return _LOGGED;
            }
            set
            {
                OnLOGGEDChanging(value);
                ReportPropertyChanging("LOGGED");
                _LOGGED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOGGED");
                OnLOGGEDChanged();
            }
        }
        private global::System.Int16 _LOGGED;
        partial void OnLOGGEDChanging(global::System.Int16 value);
        partial void OnLOGGEDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FOREIGN", "CREDITOR")]
        public EntityCollection<CREDITOR> CREDITORs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CREDITOR>("ARModel.FOREIGN", "CREDITOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CREDITOR>("ARModel.FOREIGN", "CREDITOR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_PayMent_LastModifiedBy_UserId", "PAYMENT")]
        public EntityCollection<PAYMENT> PAYMENTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PAYMENT>("ARModel.FK_PayMent_LastModifiedBy_UserId", "PAYMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PAYMENT>("ARModel.FK_PayMent_LastModifiedBy_UserId", "PAYMENT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_AR_LastModifiedBy_UserId", "RECEIVABLE")]
        public EntityCollection<RECEIVABLE> RECEIVABLEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RECEIVABLE>("ARModel.FK_AR_LastModifiedBy_UserId", "RECEIVABLE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RECEIVABLE>("ARModel.FK_AR_LastModifiedBy_UserId", "RECEIVABLE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_Sales_LastModifiedBy_UserId", "SALE")]
        public EntityCollection<SALE> SALES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SALE>("ARModel.FK_Sales_LastModifiedBy_UserId", "SALE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SALE>("ARModel.FK_Sales_LastModifiedBy_UserId", "SALE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_ReceivableInterest_UserId", "RECEIVABLEINTEREST")]
        public EntityCollection<RECEIVABLEINTEREST> RECEIVABLEINTERESTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RECEIVABLEINTEREST>("ARModel.FK_ReceivableInterest_UserId", "RECEIVABLEINTEREST");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RECEIVABLEINTEREST>("ARModel.FK_ReceivableInterest_UserId", "RECEIVABLEINTEREST", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_UserLog_UserId", "USERLOG")]
        public EntityCollection<USERLOG> USERLOGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USERLOG>("ARModel.FK_UserLog_UserId", "USERLOG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USERLOG>("ARModel.FK_UserLog_UserId", "USERLOG", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ARModel", Name="USERLOG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USERLOG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USERLOG object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dATETIMELOGIN">Initial value of the DATETIMELOGIN property.</param>
        public static USERLOG CreateUSERLOG(global::System.Int32 id, global::System.DateTime dATETIMELOGIN)
        {
            USERLOG uSERLOG = new USERLOG();
            uSERLOG.ID = id;
            uSERLOG.DATETIMELOGIN = dATETIMELOGIN;
            return uSERLOG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private Nullable<global::System.Int32> _USERID;
        partial void OnUSERIDChanging(Nullable<global::System.Int32> value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATETIMELOGIN
        {
            get
            {
                return _DATETIMELOGIN;
            }
            set
            {
                OnDATETIMELOGINChanging(value);
                ReportPropertyChanging("DATETIMELOGIN");
                _DATETIMELOGIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATETIMELOGIN");
                OnDATETIMELOGINChanged();
            }
        }
        private global::System.DateTime _DATETIMELOGIN;
        partial void OnDATETIMELOGINChanging(global::System.DateTime value);
        partial void OnDATETIMELOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATETIMELOGOUT
        {
            get
            {
                return _DATETIMELOGOUT;
            }
            set
            {
                OnDATETIMELOGOUTChanging(value);
                ReportPropertyChanging("DATETIMELOGOUT");
                _DATETIMELOGOUT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATETIMELOGOUT");
                OnDATETIMELOGOUTChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATETIMELOGOUT;
        partial void OnDATETIMELOGOUTChanging(Nullable<global::System.DateTime> value);
        partial void OnDATETIMELOGOUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BROWSER
        {
            get
            {
                return _BROWSER;
            }
            set
            {
                OnBROWSERChanging(value);
                ReportPropertyChanging("BROWSER");
                _BROWSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BROWSER");
                OnBROWSERChanged();
            }
        }
        private global::System.String _BROWSER;
        partial void OnBROWSERChanging(global::System.String value);
        partial void OnBROWSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPADD
        {
            get
            {
                return _IPADD;
            }
            set
            {
                OnIPADDChanging(value);
                ReportPropertyChanging("IPADD");
                _IPADD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPADD");
                OnIPADDChanged();
            }
        }
        private global::System.String _IPADD;
        partial void OnIPADDChanging(global::System.String value);
        partial void OnIPADDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ARModel", "FK_UserLog_UserId", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_UserLog_UserId", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_UserLog_UserId", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("ARModel.FK_UserLog_UserId", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("ARModel.FK_UserLog_UserId", "USER", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
